### ISSUE TITLE
Sale price set to 0

### ISSUE THREAD

**Issue by gareth-gillman** [codekipple/wp-e-commerce-to-woocommerce-converter#3]
When doing the import, the sale price for each product is set to 0, which sets all the products to free, it's not a big deal for small sites but for larger (2000+ products) it can be a pain.

One nice feature that would be nice is to copy the images across too

Overall, this plugin has saved me a lot of hassle but thought I would flag up this issue.

**Comment by codekipple** [comment]
Thanks @gareth-gillman feel free to submit a pull request and I'll merge it. I never use this repo anymore and really just leave it here for reference. I used it when converting a shop about 6 or 7 years ago and haven't had to do it since. Some people other than me have added extra code since then.

**Comment by ashishpadhy** [comment]
Hi can you direct me the extra codes others have edited to enhance this plugins functionality. It will be really helpful.

**Comment by codekipple** [comment]
@ashishpadhy all the extra code has been merged.

I'm not really maintaining this repo as it's never going to be useful for me again. Both plugins will have changed a lot so things like the sale price problem are bound to crop up.

Happy to merge any pull requests to improve the repo though.

**Comment by gareth-gillman** [comment]
I am going to spend some time (after finally finishing the project I used the plugin for) to fix the 2 issues I came up across and will merge them soon :)

**Comment by codekipple** [comment]
@gareth-gillman Nice one! glad the code helped a bit even with the bugs in it.

**Comment by gareth-gillman** [comment]
Saved me a lot of time, was less than 100 products so not difficult to work around the bugs, they were just inconvemient which should easily be fixed and help others :)

**Comment by codekipple** [comment]
I recent fork of this plugin has been created by @jbeales. They seem to have fixed this issue along with a lot of other improvements.
https://github.com/jbeales/wp-e-commerce-to-woocommerce-converter/commit/c76866b2fd9156f6f2645803ca5e52b7ce863671

Users are probably better off using the new fork as I don't maintain this plugin anymore.
https://github.com/jbeales/wp-e-commerce-to-woocommerce-converter
